version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-codestyle:
    executor: python/default
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 documents SuperKrutoyDocumentooborot web --max-line-length=120

workflows:
  main:
    jobs:
      - test-codestyle
